version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 277707114497.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t vite-react-app .
      - docker tag vite-react-app:latest 277707114497.dkr.ecr.us-east-1.amazonaws.com/vite-react-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 277707114497.dkr.ecr.us-east-1.amazonaws.com/vite-react-app:latest

artifacts:
  files: '**/*'
